### PR TITLE
Update 2016-06-16-macdeploy2016.md

### PR DESCRIPTION
**Pull request by clburlison**
fix hyperlink error for outset
fix hyperlink XY Problem

---

It's really sad that I have to read your blog at work via the raw markdown. https://macops.ca/ is blocked 😭 

However it does make catching hyperlink errors easier.

### CODE REVIEW

**Comment by timsutton** [comment]
Thank you!

**Comment by timsutton** [comment]
Just fixed XY problem link again, was relative

**Comment by clburlison** [comment]
Ah, makes sense I was basing it off the links already in that post. One more update for Greg's pref video. It needs a `http://`.

**Comment by timsutton** [comment]
Oops. Thanks!

**Pull request merged**
